title: ABOUT
url: "http://basyiri.my.id"
baseurl: "/en"

footer: yes
footer_url: "https://basyiri.my.id/"
footer_text: "Azhar Basyiri Hartono"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "https://basyiri.my.id/en/resume"
 - name: "Contact"
   link: "https://basyiri.my.id/en/contact"
